
package org.tipprunde.model.ws.openliga;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Sportsdata", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", wsdlLocation = "http://www.OpenLigaDB.de/Webservices/Sportsdata.asmx?WSDL")
public class Sportsdata
    extends Service
{

    private final static URL SPORTSDATA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.tipprunde.model.ws.openliga.Sportsdata.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.tipprunde.model.ws.openliga.Sportsdata.class.getResource(".");
            url = new URL(baseUrl, "http://www.OpenLigaDB.de/Webservices/Sportsdata.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.OpenLigaDB.de/Webservices/Sportsdata.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SPORTSDATA_WSDL_LOCATION = url;
    }

    public Sportsdata(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Sportsdata() {
        super(SPORTSDATA_WSDL_LOCATION, new QName("http://msiggi.de/Sportsdata/Webservices", "Sportsdata"));
    }

    /**
     * 
     * @return
     *     returns SportsdataSoap
     */
    @WebEndpoint(name = "SportsdataSoap")
    public SportsdataSoap getSportsdataSoap() {
        return super.getPort(new QName("http://msiggi.de/Sportsdata/Webservices", "SportsdataSoap"), SportsdataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SportsdataSoap
     */
    @WebEndpoint(name = "SportsdataSoap")
    public SportsdataSoap getSportsdataSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://msiggi.de/Sportsdata/Webservices", "SportsdataSoap"), SportsdataSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns SportsdataSoap
     */
    @WebEndpoint(name = "SportsdataSoap12")
    public SportsdataSoap getSportsdataSoap12() {
        return super.getPort(new QName("http://msiggi.de/Sportsdata/Webservices", "SportsdataSoap12"), SportsdataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SportsdataSoap
     */
    @WebEndpoint(name = "SportsdataSoap12")
    public SportsdataSoap getSportsdataSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://msiggi.de/Sportsdata/Webservices", "SportsdataSoap12"), SportsdataSoap.class, features);
    }

}
