
package org.tipprunde.model.ws.openliga;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SportsdataSoap", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SportsdataSoap {


    /**
     * Gibt eine Struktur aller verfügbaren Ligen zurück! Erwartet keine Parameter
     * 
     * @return
     *     returns de.hekit.tg.model.ws.openliga.ArrayOfLeague
     */
    @WebMethod(operationName = "GetAvailLeagues", action = "http://msiggi.de/Sportsdata/Webservices/GetAvailLeagues")
    @WebResult(name = "GetAvailLeaguesResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetAvailLeagues", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetAvailLeagues")
    @ResponseWrapper(localName = "GetAvailLeaguesResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetAvailLeaguesResponse")
    public ArrayOfLeague getAvailLeagues();

    /**
     * Gibt eine Struktur des nächsten anstehenden Spieles der als Parameter zu übergebenden Liga zurueck.
     * 
     * @param leagueShortcut
     * @return
     *     returns de.hekit.tg.model.ws.openliga.Matchdata
     */
    @WebMethod(operationName = "GetNextMatch", action = "http://msiggi.de/Sportsdata/Webservices/GetNextMatch")
    @WebResult(name = "GetNextMatchResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetNextMatch", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetNextMatch")
    @ResponseWrapper(localName = "GetNextMatchResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetNextMatchResponse")
    public Matchdata getNextMatch(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut);

    /**
     * Gibt eine Struktur des zuletzt ausgetragenen Spieles der als Parameter zu übergebenden Liga zurueck.
     * 
     * @param leagueShortcut
     * @return
     *     returns de.hekit.tg.model.ws.openliga.Matchdata
     */
    @WebMethod(operationName = "GetLastMatch", action = "http://msiggi.de/Sportsdata/Webservices/GetLastMatch")
    @WebResult(name = "GetLastMatchResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetLastMatch", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetLastMatch")
    @ResponseWrapper(localName = "GetLastMatchResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetLastMatchResponse")
    public Matchdata getLastMatch(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut);

    /**
     * Gibt die aktuelle groupOrderID (entspricht z.B. bei der Fussball-Bundesliga dem 'Spieltag') des als Parameter zu übergebenden leagueShortcuts (z.B. 'bl1') aus. Der aktuelle Spieltag wird jeweils zur Hälfte der Zeit zwischen dem letzten Spiel des letzten Spieltages und dem ersten Spiel des nächsten Spieltages erhöht.
     * 
     * @param leagueShortcut
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetCurrentGroupOrderID", action = "http://msiggi.de/Sportsdata/Webservices/GetCurrentGroupOrderID")
    @WebResult(name = "GetCurrentGroupOrderIDResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetCurrentGroupOrderID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetCurrentGroupOrderID")
    @ResponseWrapper(localName = "GetCurrentGroupOrderIDResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetCurrentGroupOrderIDResponse")
    public int getCurrentGroupOrderID(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut);

    /**
     * Gibt die aktuelle Group (entspricht z.B. bei der Fussball-Bundesliga dem 'Spieltag') des als Parameter zu übergebenden leagueShortcuts (z.B. 'bl1') aus. Der aktuelle Spieltag wird jeweils zur Hälfte der Zeit zwischen dem letzten Spiel des letzten Spieltages und dem ersten Spiel des nächsten Spieltages erhöht.
     * 
     * @param leagueShortcut
     * @return
     *     returns de.hekit.tg.model.ws.openliga.Group
     */
    @WebMethod(operationName = "GetCurrentGroup", action = "http://msiggi.de/Sportsdata/Webservices/GetCurrentGroup")
    @WebResult(name = "GetCurrentGroupResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetCurrentGroup", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetCurrentGroup")
    @ResponseWrapper(localName = "GetCurrentGroupResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetCurrentGroupResponse")
    public Group getCurrentGroup(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut);

    /**
     * Gibt eine Struktur von Sport-Spieldaten zurueck. Als Parameter werden eine groupOrderID (zu entnehmen aus GetAvailGroups, entspricht z.B. bei der Fussball-Bundesliga dem Spieltag), der Liga-Shortcut (z.B. 'bl1') sowie die Saison (aus GetAvailLeagues, z.B. '2009') erwartet. Das Ergebnis dieser Abfrage unterliegt einem serverseitigen Cache von 60 Sekunden.
     * 
     * @param groupOrderID
     * @param leagueShortcut
     * @param leagueSaison
     * @return
     *     returns de.hekit.tg.model.ws.openliga.ArrayOfMatchdata
     */
    @WebMethod(operationName = "GetMatchdataByGroupLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetMatchdataByGroupLeagueSaison")
    @WebResult(name = "GetMatchdataByGroupLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetMatchdataByGroupLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetMatchdataByGroupLeagueSaison")
    @ResponseWrapper(localName = "GetMatchdataByGroupLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetMatchdataByGroupLeagueSaisonResponse")
    public ArrayOfMatchdata getMatchdataByGroupLeagueSaison(
        @WebParam(name = "groupOrderID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int groupOrderID,
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueSaison);

    /**
     * Gibt eine Struktur von Sport-Spieldaten zurueck. Die Beginn-Zeit der ausgegebenen Spieldaten liegt zwischen den als Parameter zu übergebenen DateTime-Werten. (fromDateTime <= matchBeginDateTime < toDateTime)Als weiterer Parameter wird der Liga-Shortcut (z.B. 'bl1') erwartet.
     * 
     * @param toDateTime
     * @param leagueShortcut
     * @param fromDateTime
     * @return
     *     returns de.hekit.tg.model.ws.openliga.ArrayOfMatchdata
     */
    @WebMethod(operationName = "GetMatchdataByLeagueDateTime", action = "http://msiggi.de/Sportsdata/Webservices/GetMatchdataByLeagueDateTime")
    @WebResult(name = "GetMatchdataByLeagueDateTimeResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetMatchdataByLeagueDateTime", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetMatchdataByLeagueDateTime")
    @ResponseWrapper(localName = "GetMatchdataByLeagueDateTimeResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetMatchdataByLeagueDateTimeResponse")
    public ArrayOfMatchdata getMatchdataByLeagueDateTime(
        @WebParam(name = "fromDateTime", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        XMLGregorianCalendar fromDateTime,
        @WebParam(name = "toDateTime", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        XMLGregorianCalendar toDateTime,
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut);

    /**
     * Gibt eine Struktur von Matches zurück, bei welchen die als Parameter übergebenen Teams gegeneinander spielten.
     * 
     * @param teamID1
     * @param teamID2
     * @return
     *     returns de.hekit.tg.model.ws.openliga.ArrayOfMatchdata
     */
    @WebMethod(operationName = "GetMatchdataByTeams", action = "http://msiggi.de/Sportsdata/Webservices/GetMatchdataByTeams")
    @WebResult(name = "GetMatchdataByTeamsResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetMatchdataByTeams", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetMatchdataByTeams")
    @ResponseWrapper(localName = "GetMatchdataByTeamsResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetMatchdataByTeamsResponse")
    public ArrayOfMatchdata getMatchdataByTeams(
        @WebParam(name = "teamID1", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int teamID1,
        @WebParam(name = "teamID2", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int teamID2);

    /**
     * Gibt eine Struktur von Sport-Spieldaten aller Spiele der Liga pro Saison zurueck. Als Parameter werden der Liga-Shortcut (z.B. 'bl1') sowie die Saison (aus GetAvailLeagues, z.B. '2007') erwartet.
     * 
     * @param leagueShortcut
     * @param leagueSaison
     * @return
     *     returns de.hekit.tg.model.ws.openliga.ArrayOfMatchdata
     */
    @WebMethod(operationName = "GetMatchdataByLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetMatchdataByLeagueSaison")
    @WebResult(name = "GetMatchdataByLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetMatchdataByLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetMatchdataByLeagueSaison")
    @ResponseWrapper(localName = "GetMatchdataByLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetMatchdataByLeagueSaisonResponse")
    public ArrayOfMatchdata getMatchdataByLeagueSaison(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueSaison);

    /**
     * Gibt einen serialisiertes JSON-Objekt von Sport-Spieldaten zurueck. Als Parameter werden eine groupOrderID (zu entnehmen aus GetAvailGroups, entspricht z.B. bei der Fussball-Bundesliga dem Spieltag), der Liga-Shortcut (z.B. 'bl1') sowie die Saison (aus GetAvailLeagues, z.B. '2009') erwartet. Das Ergebnis dieser Abfrage unterliegt einem serverseitigen Cache von 60 Sekunden.
     * 
     * @param groupOrderID
     * @param leagueShortcut
     * @param leagueSaison
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMatchdataByGroupLeagueSaisonJSON", action = "http://msiggi.de/Sportsdata/Webservices/GetMatchdataByGroupLeagueSaisonJSON")
    @WebResult(name = "GetMatchdataByGroupLeagueSaisonJSONResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetMatchdataByGroupLeagueSaisonJSON", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetMatchdataByGroupLeagueSaisonJSON")
    @ResponseWrapper(localName = "GetMatchdataByGroupLeagueSaisonJSONResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetMatchdataByGroupLeagueSaisonJSONResponse")
    public String getMatchdataByGroupLeagueSaisonJSON(
        @WebParam(name = "groupOrderID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int groupOrderID,
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueSaison);

    /**
     * Gibt eine Struktur deutscher Fussball-Spieldaten zurueck. Diese Methode steht nur noch aus Gründen der Kompatibilität zu älteren Applikationen zur Verfügung. Bitte nutzen sie vorrangig die GetMatchdata... - Methoden!
     * 
     * @param userkennung
     * @param liga
     * @param spieltag
     * @param saison
     * @return
     *     returns de.hekit.tg.model.ws.openliga.ArrayOfFussballdaten
     */
    @WebMethod(operationName = "GetFusballdaten", action = "http://msiggi.de/Sportsdata/Webservices/GetFusballdaten")
    @WebResult(name = "GetFusballdatenResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetFusballdaten", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetFusballdaten")
    @ResponseWrapper(localName = "GetFusballdatenResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetFusballdatenResponse")
    public ArrayOfFussballdaten getFusballdaten(
        @WebParam(name = "Spieltag", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int spieltag,
        @WebParam(name = "Liga", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String liga,
        @WebParam(name = "Saison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int saison,
        @WebParam(name = "Userkennung", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String userkennung);

    /**
     * Gibt eine Struktur des Spieles der als Parameter zu übergebenden MatchID zurueck.
     * 
     * @param matchID
     * @return
     *     returns de.hekit.tg.model.ws.openliga.Matchdata
     */
    @WebMethod(operationName = "GetMatchByMatchID", action = "http://msiggi.de/Sportsdata/Webservices/GetMatchByMatchID")
    @WebResult(name = "GetMatchByMatchIDResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetMatchByMatchID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetMatchByMatchID")
    @ResponseWrapper(localName = "GetMatchByMatchIDResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetMatchByMatchIDResponse")
    public Matchdata getMatchByMatchID(
        @WebParam(name = "MatchID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int matchID);

    /**
     * Gibt eine Liste aller Teams der als Parameter zu übergebenden Liga + Saison zurueck.
     * 
     * @param leagueShortcut
     * @param leagueSaison
     * @return
     *     returns de.hekit.tg.model.ws.openliga.ArrayOfTeam
     */
    @WebMethod(operationName = "GetTeamsByLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetTeamsByLeagueSaison")
    @WebResult(name = "GetTeamsByLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetTeamsByLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetTeamsByLeagueSaison")
    @ResponseWrapper(localName = "GetTeamsByLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetTeamsByLeagueSaisonResponse")
    public ArrayOfTeam getTeamsByLeagueSaison(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueSaison);

    /**
     * Gibt eine Liste der bereits eingetragenen Spiel-Einteilungen (Spieltag, Vorrunde, Finale, ...) der als Parameter zu übergebenden Liga + Saison zurueck.
     * 
     * @param leagueShortcut
     * @param leagueSaison
     * @return
     *     returns de.hekit.tg.model.ws.openliga.ArrayOfGroup
     */
    @WebMethod(operationName = "GetAvailGroups", action = "http://msiggi.de/Sportsdata/Webservices/GetAvailGroups")
    @WebResult(name = "GetAvailGroupsResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetAvailGroups", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetAvailGroups")
    @ResponseWrapper(localName = "GetAvailGroupsResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetAvailGroupsResponse")
    public ArrayOfGroup getAvailGroups(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueSaison);

    /**
     * Gibt eine Liste der verfügbaren Sportarten, für welche gültige Ligen bestehen, zurück. Erwartet keine Parameter
     * 
     * @return
     *     returns de.hekit.tg.model.ws.openliga.ArrayOfSport
     */
    @WebMethod(operationName = "GetAvailSports", action = "http://msiggi.de/Sportsdata/Webservices/GetAvailSports")
    @WebResult(name = "GetAvailSportsResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetAvailSports", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetAvailSports")
    @ResponseWrapper(localName = "GetAvailSportsResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetAvailSportsResponse")
    public ArrayOfSport getAvailSports();

    /**
     * Gibt eine Struktur aller verfügbaren Ligen für die zu übergebende SportID zurück. Diese ist aus 'GetAvailSports()' zu entnehmen!
     * 
     * @param sportID
     * @return
     *     returns de.hekit.tg.model.ws.openliga.ArrayOfLeague
     */
    @WebMethod(operationName = "GetAvailLeaguesBySports", action = "http://msiggi.de/Sportsdata/Webservices/GetAvailLeaguesBySports")
    @WebResult(name = "GetAvailLeaguesBySportsResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetAvailLeaguesBySports", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetAvailLeaguesBySports")
    @ResponseWrapper(localName = "GetAvailLeaguesBySportsResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetAvailLeaguesBySportsResponse")
    public ArrayOfLeague getAvailLeaguesBySports(
        @WebParam(name = "sportID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int sportID);

    /**
     * Gibt eine Liste aller Goals des als Parameter zu übergebenden Match zurueck.
     * 
     * @param matchID
     * @return
     *     returns de.hekit.tg.model.ws.openliga.ArrayOfGoal
     */
    @WebMethod(operationName = "GetGoalsByMatch", action = "http://msiggi.de/Sportsdata/Webservices/GetGoalsByMatch")
    @WebResult(name = "GetGoalsByMatchResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetGoalsByMatch", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetGoalsByMatch")
    @ResponseWrapper(localName = "GetGoalsByMatchResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetGoalsByMatchResponse")
    public ArrayOfGoal getGoalsByMatch(
        @WebParam(name = "MatchID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int matchID);

    /**
     * Gibt eine Liste aller Goals der als Parameter zu übergebenden Liga + Saison zurueck.
     * 
     * @param leagueShortcut
     * @param leagueSaison
     * @return
     *     returns de.hekit.tg.model.ws.openliga.ArrayOfGoal
     */
    @WebMethod(operationName = "GetGoalsByLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetGoalsByLeagueSaison")
    @WebResult(name = "GetGoalsByLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetGoalsByLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetGoalsByLeagueSaison")
    @ResponseWrapper(localName = "GetGoalsByLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetGoalsByLeagueSaisonResponse")
    public ArrayOfGoal getGoalsByLeagueSaison(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueSaison);

    /**
     * Gibt eine Liste der GoalGetter der als Parameter zu übergebenden Liga + Saison zurueck.
     * 
     * @param leagueShortcut
     * @param leagueSaison
     * @return
     *     returns de.hekit.tg.model.ws.openliga.ArrayOfGoalGetter
     */
    @WebMethod(operationName = "GetGoalGettersByLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetGoalGettersByLeagueSaison")
    @WebResult(name = "GetGoalGettersByLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetGoalGettersByLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetGoalGettersByLeagueSaison")
    @ResponseWrapper(localName = "GetGoalGettersByLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetGoalGettersByLeagueSaisonResponse")
    public ArrayOfGoalGetter getGoalGettersByLeagueSaison(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueSaison);

    /**
     * Gibt das Datum der letzten Änderung in der als Parameter zu übergebenden Liga + Saison zurueck. Kann verwendet werden, um clientseitg unnötige Abfragen zu vermeiden (Cache)
     * 
     * @param leagueShortcut
     * @param leagueSaison
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetLastChangeDateByLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetLastChangeDateByLeagueSaison")
    @WebResult(name = "GetLastChangeDateByLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetLastChangeDateByLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetLastChangeDateByLeagueSaison")
    @ResponseWrapper(localName = "GetLastChangeDateByLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetLastChangeDateByLeagueSaisonResponse")
    public XMLGregorianCalendar getLastChangeDateByLeagueSaison(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueSaison);

    /**
     * Gibt das Datum der letzten Änderung in der als Parameter zu übergebenden Liga + Saison zurueck. Kann verwendet werden, um clientseitg unnötige Abfragen zu vermeiden (Cache)
     * 
     * @param groupOrderID
     * @param leagueShortcut
     * @param leagueSaison
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetLastChangeDateByGroupLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetLastChangeDateByGroupLeagueSaison")
    @WebResult(name = "GetLastChangeDateByGroupLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    @RequestWrapper(localName = "GetLastChangeDateByGroupLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetLastChangeDateByGroupLeagueSaison")
    @ResponseWrapper(localName = "GetLastChangeDateByGroupLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.hekit.tg.model.ws.openliga.GetLastChangeDateByGroupLeagueSaisonResponse")
    public XMLGregorianCalendar getLastChangeDateByGroupLeagueSaison(
        @WebParam(name = "groupOrderID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int groupOrderID,
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        String leagueSaison);

}
